### PR TITLE
Coerce empty string to nil for all Primitive types except String

### PR DESCRIPTION
**Pull request by petekinnecom**

### CODE REVIEW

**Comment by petekinnecom** [comment]
Here's a reproduction of the behavior on v.1.2.5: https://github.com/petekinnecom/grape/commit/ec99d8cec24760934b3b0adc5a7ca46a139f0dfe#diff-d4c132540f49911bbd1c73264c2c738bR12

**Comment by dblock** [comment]
This does modify external behavior of interacting with an API. I think we need:

- A spec as comprehensive as https://github.com/petekinnecom/grape/commit/ec99d8cec24760934b3b0adc5a7ca46a139f0dfe#diff-d4c132540f49911bbd1c73264c2c738bR12
- A API-level spec describing the behavior in https://github.com/ruby-grape/grape/issues/2066

WDYT?

**Comment by dnesteryuk** [comment]
@dblock do you mean more integration tests? What is wrong with unit tests? :thinking: Personally, I like more unit tests, they are more focused (point to code under tests).

**Comment by dblock** [comment]
> @dblock do you mean more integration tests? What is wrong with unit tests? 🤔 Personally, I like more unit tests, they are more focused (point to code under tests).

Yes. This behavior affects what happens when you call an API, and there are no changes in tests for that external behavior. We often rely on those integration tests when we're not sure what's supposed to happen and still keep introducing regressions. Better safe than sorry. @petekinnecom if you aren't adding any I'm OK with merging this though. Just let us know?

**Comment by petekinnecom** [comment]
I've pushed a commit that has integration tests that mirror the tests found for `nil` (they are found just above in the same file I edited). The behavior for primitive types is all that's been updated here, so for other types, this just captures existing behavior.  For the exceptions here the params are not parsed as an empty string but rather cause a `400` response:

https://github.com/ruby-grape/grape/pull/2067/commits/619db09483194f27f87719d840ef23e72e7de565#diff-d4c132540f49911bbd1c73264c2c738bR533
https://github.com/ruby-grape/grape/pull/2067/commits/619db09483194f27f87719d840ef23e72e7de565#diff-d4c132540f49911bbd1c73264c2c738bR550

**Comment by dblock** [comment]
Perfect, merged. Thank you.

**Pull request merged**
