### PR TITLE
Empty optional nested array

### PR DESCRIPTION
**Pull request by ipkes**
Based on [issue](https://github.com/ruby-grape/grape/issues/723) and [tests](https://github.com/ruby-grape/grape/pull/911)
1. Some test modification
2. Possible solution

### CODE REVIEW

**Comment by ipkes** [comment]
I'm afraid solution is insufficient and needs some work here. A major problem here with digging deeper in array. Need more time to think

**Comment by dblock** [comment]
Start by rebasing and squashing this, there're a bunch of unrelated changes, hard to grok.

**Comment by ipkes** [comment]
1. correctly done rebasing
2. another spec modify, more complex example (to digging deeper)
3. and sufficient solution
----------
problem was with checking on blank, first we should check not for all elements, just for any and second sometimes we have already blank parameter and we should check it first.

**Comment by ipkes** [comment]
And for information. When I tried to find solution, I analyzed elements and parameters, which came, without complete understanding why they are coming. I can't be sure that anything else parameters will be work as well, but to already described parameters, it's ok.

**Comment by dblock** [comment]
This makes total sense to me. We want to do an `allow_blank` validation if anything is blank here. Merging.

**Comment by dblock** [comment]
Merged via https://github.com/ruby-grape/grape/commit/9a083581204a492ac7153cbd4d05e385f4a94793, thank you.

**Pull request closed without merging**
