### PR TITLE
Add spec for default value in given block

### PR DESCRIPTION
**Pull request by darren987469**
Add spec for #1681. The issue seems already fixed.

### CODE REVIEW

**Comment by dblock** [comment]
There's some dependency/ruby version changes that failed the build here. Appreciate if you could please try to fix that? Upgrading those rubies seems to be the right way to go. Thanks.

**Comment by darren987469** [comment]
I open another PR to add ruby 2.5 support and drop 2.2 support (#1813 ). After 1813 merged, I will rebase it and CI should pass.

**Comment by dblock** [comment]
Merged it, thanks @darren987469

**Comment by dblock** [comment]
Merged, thank you.

**Pull request merged**
