### PR TITLE
Fixes boolean declaration in an external helper file.

### PR DESCRIPTION
**Pull request by towanda**
See https://github.com/ruby-grape/grape/issues/1144.

### CODE REVIEW

**Comment by dblock** [comment]
Do you think you can write a test for this?

**Comment by dblock** [comment]
I also wonder if we need to check whether Boolean is already defined here. I would move the `const_set` into a function, just to make it cleaner, ala `inject_api_helpers_to_mod` and check.

**Comment by towanda** [comment]
@dblock added spec and now checks if it's defined in a separate function.

**Comment by dblock** [comment]
Great, merging.

**Pull request merged**
