### PR TITLE
Initial work adding Danger

### PR DESCRIPTION
**Pull request by orta**
**Pre-requisite**

This requires the CI ENV var `DANGER_GITHUB_API_TOKEN` to be set up, so someone has to [follow this guide](http://danger.systems/guides/getting_started.html) from "Creating a GitHub Account for Danger to use". 

I'd recommend making a new GitHub account for GrapeCI - see our [DangerCI one](https://github.com/DangerCI?tab=activity), don't give it access to any of the repos. 

Then re-build this PR. I've not made any README changes, so it should show a message about me adding one.

### CODE REVIEW

**Comment by dblock** [comment]
I've setup a `DANGER_GITHUB_API_TOKEN` env variable. Note that there're some Rails appraisal builds that will need `danger` in the Gemfile as well, eg. https://github.com/ruby-grape/grape/blob/master/gemfiles/rails_3.gemfile.

**Comment by orta** [comment]
wait, what? how did I close this?

**Comment by orta** [comment]
Can I not force-push on a fork PR?

**Comment by dblock** [comment]
You should be able to, not sure what's up.

**Pull request closed without merging**
