### PR TITLE
Updated Danger token

### PR DESCRIPTION
**Pull request by dblock**
merging #2149

### CODE REVIEW

**Comment by anakinj** [comment]
@dblock I think the public api token for Danger interaction needs to be added to the CI yml. The secrets for the repository only seem to be available for collaborators.

An example on how Danger does it: https://github.com/danger/danger/blob/master/.github/workflows/CI.yml

Also thing the API key for this repo is already in wild: https://travis-ci.org/github/ruby-grape/grape/jobs/751852078#L184

**Comment by anakinj** [comment]
This worked using the repository secrets because I tested this on my local fork on where i was the owner. But for public pull requests the secrets will be hidden. The UI for the repository secrets even state `Secrets are environment variables that are encrypted. Anyone with collaborator access to this repository can use these secrets for Actions.`

**Comment by dblock** [comment]
> @dblock I think the public api token for Danger interaction needs to be added to the CI yml. The secrets for the repository only seem to be available for collaborators.
> 
> An example on how Danger does it: https://github.com/danger/danger/blob/master/.github/workflows/CI.yml
> 
> Also think the API key for this repo is already in wild: https://travis-ci.org/github/ruby-grape/grape/jobs/751852078#L184

Thanks. I spoke to @orta and it looks like hard-coding the token is the easiest way. Seems like a miss from Github to not allow clear tokens for scenarios like these.

**Comment by anakinj** [comment]
Seems to be working now, great job.

**Pull request merged**
