### PR TITLE
Use reverse_merge

### PR DESCRIPTION
**Pull request by marshall-lee**
Similar to #1125
`Hash#reverse_merge` is conventional.

### CODE REVIEW

**Comment by dblock** [comment]
Eh, this is interesting. You need to rebase, thx.

**Comment by marshall-lee** [comment]
Rebased!

**Comment by dblock** [comment]
Rubocop offence! Needs a `rubocop -a` and a `rubocop --auto-gen-config`.

**Comment by marshall-lee** [comment]
@dblock I think I could please him :)

**Pull request merged**
