### PR TITLE
Silence warnings

### LINKED ISSUE #1582: warnings when running tests
I imagine I am missing a config option or something, but I can't figure out why I am seeing these errors when running tests using `Rack::Test` against a grape app:

```
/ruby/gems/2.3.0/bundler/gems/grape-4004faf0bf46/lib/grape/validations/validators/values.rb:21: warning: instance variable @excepts not initialized
/ruby/gems/2.3.0/bundler/gems/grape-4004faf0bf46/lib/grape/validations/validators/values.rb:31: warning: instance variable @proc not initialized
/ruby/gems/2.3.0/bundler/gems/grape-4004faf0bf46/lib/grape/validations/validators/values.rb:21: warning: instance variable @excepts not initialized
/ruby/gems/2.3.0/bundler/gems/grape-4004faf0bf46/lib/grape/validations/validators/values.rb:21: warning: instance variable @excepts not initialized
/ruby/gems/2.3.0/bundler/gems/grape-4004faf0bf46/lib/grape/validations/validators/values.rb:31: warning: instance variable @proc not initialized
/ruby/gems/2.3.0/bundler/gems/grape-4004faf0bf46/lib/grape/dsl/inside_route.rb:237: warning: instance variable @file not initialized
/ruby/gems/2.3.0/bundler/gems/grape-4004faf0bf46/lib/grape/dsl/inside_route.rb:147: warning: instance variable @status not initialized
```

Anyone have any idea about how to get rid of these?

### PR DESCRIPTION
**Pull request by thogg4**
@dblock maybe something like this?

fixes #1582

### CODE REVIEW

**Comment by dblock** [comment]
Better! Lets finish this.

If this lets us turn on warnings as errors in the build that should be part of this. 

If it fully resolves https://github.com/ruby-grape/grape/issues/1582, it needs a CHANGELOG entry.

Fix the build, needs `rubocop -a` and `rubocop --auto-gen-config`.

Remove things that are unrelated to this PR.

Squash.

**Comment by thogg4** [comment]
@dblock how is that?

**Comment by dblock** [comment]
This looks great. Before I merge this, what is the effect of `disable_warnings` when using `Mash`? This is different from uninitialized variables warnings.

**Comment by thogg4** [comment]
@dblock that is in conjunction with this pull request in hashie: https://github.com/intridea/hashie/pull/395

They have you subclass `Mash` so you can disable warnings that you cause when you use it.

**Comment by dblock** [comment]
I understand but why do we ever want this? Don't you want to know when you're assigning a parameter that overrides something built in?

**Comment by thogg4** [comment]
@dblock you're right. i have removed that.

**Comment by dblock** [comment]
I'll wait on 🍏  to re-review.

**Comment by dblock** [comment]
Merged, thanks.

**Pull request merged**
