### PR TITLE
Improved README For Mounting Multiple Version

### PR DESCRIPTION
**Pull request by przbadu**
- remove unwanted piece of codes
- improve documentation following (http://code.dblock.org/2013/07/19/evolving-apis-using-grape-api-versioning.html)

### CODE REVIEW

**Comment by przbadu** [comment]
@dblock: I updated README file, but getting travis-ci failing errors. 3 spec are failing, and looks like we can improve expectation for that. Need to check for other errors

**Comment by przbadu** [comment]
`3 failure` in master branch

**Comment by dblock** [comment]
Please rebase, squash, fix specs. Given the ^^^ maybe http://code.dblock.org/2015/08/31/getting-out-of-your-first-git-mess.html could help?

**Comment by przbadu** [comment]
I am trying to fix failing spec and will rebase, squash from your referenced article and create a pull request. Thanks for your help 👍

**Pull request closed without merging**
