### PR TITLE
Add test for OPTIONS and HEAD requests with catch-all

### PR DESCRIPTION
**Pull request by namusyaka**
ref #1057
I've cherry-picked @ekampp's commit and fixed a little bit.
Thoughts?

### CODE REVIEW

**Comment by ekampp** [comment]
[OPTIONS requests should return 200 OK](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html)

**Comment by namusyaka** [comment]
Well, `OPTIONS` seems not to have the restriction of status codes.
Our default `OPTIONS` routes are defined at [this line](https://github.com/ruby-grape/grape/blob/master/lib/grape/api.rb#L180-L186), and this means that a response of the route will be empty. 
So I guess `204` status is reasonable, right?

**Comment by ekampp** [comment]
204 is reasonable for an empty response. But I'm reading that it should return 200 OK. But either way getting this to pass would be an improvement :+1:

**Comment by dblock** [comment]
Very good, the passing spec is a merge. Lets close the related bug and review whether we want to change the status code here (open new issues as appropriate).

**Comment by dblock** [comment]
This possibly needs a CHANGELOG entry since I believe this was a known bug now fixed, @namusyaka please.

**Pull request merged**
