### PR TITLE
make route detail = notes

### PR DESCRIPTION
**Pull request by calfzhou**
ref #920

### CODE REVIEW

**Comment by dblock** [comment]
This seems like a hack for grape-swagger, I don't think we want to merge this as is. Maybe this is something that we want in grape-swagger?

If there's a compelling argument to merge it, this needs a CHANGELOG entry and tests.

**Comment by dblock** [comment]
Bump @calfzhou.

**Comment by rngtng** [comment]
:-1: this will fix it instead: https://github.com/tim-vandecasteele/grape-swagger/pull/286

**Comment by dblock** [comment]
:+1: @rngtng I am going to close this without merging.

**Pull request closed without merging**
