### PR TITLE
require core_ext/object/blank

### PR DESCRIPTION
**Pull request by marshall-lee**
This one is for #1121

`active_support/core_ext/object/conversions` was the most heavy dependency that slows everything **twice**. 
What do you think about cutting `ActiveSupport` usage to minimum? Ideally, not depend on it at all.

### CODE REVIEW

**Comment by marshall-lee** [comment]
Before this patch:
```
This is ApacheBench, Version 2.3 <$Revision: 1604373 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)


Server Software:        Goliath
Server Hostname:        localhost
Server Port:            9000

Document Path:          /
Document Length:        13 bytes

Concurrency Level:      100
Time taken for tests:   6.127 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      106000 bytes
HTML transferred:       13000 bytes
Requests per second:    163.21 [#/sec] (mean)
Time per request:       612.710 [ms] (mean)
Time per request:       6.127 [ms] (mean, across all concurrent requests)
Transfer rate:          16.89 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.5      0       2
Processing:    90  590  86.1    608     688
Waiting:       28  533  94.8    548     628
Total:         90  590  86.0    609     688

Percentage of the requests served within a certain time (ms)
  50%    609
  66%    612
  75%    618
  80%    619
  90%    625
  95%    626
  98%    626
  99%    628
 100%    688 (longest request)
```

**Comment by marshall-lee** [comment]
After this patch:
```
This is ApacheBench, Version 2.3 <$Revision: 1604373 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)


Server Software:        Goliath
Server Hostname:        localhost
Server Port:            9000

Document Path:          /
Document Length:        13 bytes

Concurrency Level:      100
Time taken for tests:   3.151 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      106000 bytes
HTML transferred:       13000 bytes
Requests per second:    317.40 [#/sec] (mean)
Time per request:       315.059 [ms] (mean)
Time per request:       3.151 [ms] (mean, across all concurrent requests)
Transfer rate:          32.86 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.4      0       2
Processing:    69  304  41.5    312     351
Waiting:       36  273  49.5    282     320
Total:         70  304  41.5    313     352

Percentage of the requests served within a certain time (ms)
  50%    313
  66%    315
  75%    316
  80%    317
  90%    321
  95%    323
  98%    325
  99%    352
 100%    352 (longest request)
```

**Comment by dblock** [comment]
That's fairly impressive. Obviously we should feel good about cutting deep for performance purposes.

**Comment by marshall-lee** [comment]
`ActiveSupport` dependencies mostly affect the entire application, not the components alone.

Simple benchmark `ruby benchmark/simple.rb` hasn't shown better results.

**Comment by marshall-lee** [comment]
*after* / *before* benchmarks above is a goliath benchmark by @yokas from #1121

**Pull request merged**
