### PR TITLE
Fix Coveralls code coverage

### LINKED ISSUE #2061: Fix code coverage
https://coveralls.io/github/ruby-grape/grape?branch=master

### PR DESCRIPTION
**Pull request by duffn**
Currently
```
Randomized with seed 1113
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Couldn't find a repository matching this job.
Coverage is at 98.94%.
Coverage report sent to Coveralls.
```

On my fork after adding the Coveralls token
```
Randomized with seed 57600
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job ##8.1
[Coveralls] https://coveralls.io/jobs/101153293
Coverage is at 98.94%.
Coverage report sent to Coveralls.
```

- Reference a good comment: https://github.com/lemurheavy/coveralls-public/issues/1613#issuecomment-1028302521
- `coveralls-reborn` using `COVERALLS_REPO_TOKEN` https://github.com/tagliala/coveralls-ruby-reborn/blob/e17e7c4c7776fb2f74a225905d421f01382f3f2b/lib/coveralls/configuration.rb#L22
- The service name in `.coveralls.yml` must be something, though in this case it doesn't have any special meaning https://docs.coveralls.io/api-reference
- _NOTE_: The repo token here (https://coveralls.io/github/ruby-grape/grape/settings) must be set as a secret in this repository for this to work

Closes #2061.

### CODE REVIEW

**Comment by dblock** [comment]
I added `COVERALLS_REPO_TOKEN` here.

**Comment by dblock** [comment]
Merged. Could you please check that `master` got coverage successfully now?

**Comment by dblock** [comment]
https://coveralls.io/jobs/101222049

**Comment by dblock** [comment]
@duffn see https://github.com/lemurheavy/coveralls-public/issues/1505, maybe you'll find a solution to this?

**Comment by duffn** [comment]
I’m not intimately familiar with Coveralls, but I’ll take a look at what’s going on here.

**Pull request merged**
