### PR TITLE
Explicitly require ActiveSupport's Hash#except

### PR DESCRIPTION
**Pull request by wagenet**
This allows Grape to be run with ActiveSupport 3, without Rails.
In ActiveSupport 4, this file ended up being required as a
dependency of `active_support/core_ext/object/conversions`. Also,
Rails itself includes this file.

### CODE REVIEW

**Comment by wagenet** [comment]
Fixes #1087

**Comment by dblock** [comment]
I think there should be a CHANGELOG entry for this, please, via `--amend`.

**Comment by wagenet** [comment]
@dblock good call

**Comment by wagenet** [comment]
@dblock done

**Comment by dblock** [comment]
I am going to be pedantic about this CHANGELOG, apologies :) This fixes running grape with ActiveSupport 3.x, right? Lets write this in the CHANGELOG as that fix?

**Comment by wagenet** [comment]
@dblock no need to apologize for pedantry :)

**Comment by wagenet** [comment]
@dblock updated again. Fingers crossed :)

**Comment by dblock** [comment]
I like it, merging.

**Pull request merged**
