### PR TITLE
Update rubocop to 1.41.0

### PR DESCRIPTION
**Pull request by ericproulx**
Updating rubocop to latest version which is 1.41.0

### CODE REVIEW

**Comment by ericproulx** [comment]
Danger credentials doesn't work : 401 - Bad credentials

**Comment by dblock** [comment]
> Danger credentials doesn't work : 401 - Bad credentials

The account that owned those got reset by GitHub last week :( I'd like to replace this with something like https://github.com/dangoslen/changelog-enforcer to avoid this happening in the future, want to help?

**Comment by dblock** [comment]
https://github.com/ruby-grape/grape/pull/2291 rebase?

**Comment by ericproulx** [comment]
@dblock did the rebase and put 1.41 since a version came out since I've created the PR

**Comment by dblock** [comment]
Looks like some CI is failing on older rubies, probably unrelated but I'd rather not merge, care to take a look?

**Comment by ericproulx** [comment]
```
Bundler found conflicting requirements for the Ruby version:
    In rack1.gemfile:
      rubocop (= 1.41.0) was resolved to 1.41.0, which depends on
        Ruby (>= 2.6.0)
  
    Current Ruby version:
      Ruby (= 2.5.9)
```

**Comment by dblock** [comment]
Looks like we're dropping support for Ruby 2.5 here? Ruby 2.5 is EOL already, so that's ok. Make the necessary changes as needed (change 2.5 to 2.6 or newer as appropriate), get CI to green, and note in CHANGELOG something like "Dropped support for Ruby 2.5".

**Comment by ericproulx** [comment]
> Looks like we're dropping support for Ruby 2.5 here? Ruby 2.5 is EOL already, so that's ok. Make the necessary changes as needed (change 2.5 to 2.6 or newer as appropriate), get CI to green, and note in CHANGELOG something like "Dropped support for Ruby 2.5".

[Rubocop](https://github.com/rubocop/rubocop/commit/1a60305ffbeb6128d29b631628167e832e21bd9f) drop support for ruby 2.5 in April.

**Pull request merged**
