### PR TITLE
Expand test coverage of undocumented functionality

### PR DESCRIPTION
**Pull request by jacobherrington**
In an interview recently, I was given the Grape repository sans the
content of this method as a technical screening question. The task was
to discover what had been removed from the project and re-implement the
missing code using only the test suite.

It was actually fairly difficult to re-implement this method because
there are a couple of untested responsibilities. I think this is a
fairly integral component of the framework, so it makes sense to fully
test its functionality.

### CODE REVIEW

**Comment by jacobherrington** [comment]
I see this as improving documentation, but I'm happy to add a changelog entry if necessary.

**Comment by dblock** [comment]
Thanks for the test!

**Comment by dblock** [comment]
Pretty wild interview test idea if you ask me, btw! How did you do @jacobherrington?

**Comment by jacobherrington** [comment]
@dblock I actually really liked it! I did well enough, but joined another company! (check my account 😉)

**Pull request merged**
