### PR TITLE
The `include_parent_namespaces` option is broken

### PR DESCRIPTION
**Pull request by faucct**
Fixed the tests to point that out.

### CODE REVIEW

**Comment by dblock** [comment]
Just to save us time, what's the simplest example of where it's broken? Want to attempt a fix and it looks like we don't document it, would love a README entry.

**Comment by faucct** [comment]
The tests have the example:

```ruby
        namespace :something do
          params do
            requires :id, type: Integer
          end
          resource ':id' do
            params do
              requires :happy
              optional :days
            end
            get '/test' do
              {
                params: params,
                declared_params: declared(params, include_parent_namespaces: false)
              }
            end
          end
        end
```

**Comment by dblock** [comment]
What does the above output and what do you expect?

**Comment by faucct** [comment]
Can you check the updated tests, please? It clearly states what behavior I do expect and in which case.

**Comment by dblock** [comment]
Makes sense. If someone is trying to fix this, lets please add specs for nested namespaces as well (parent of parent) and document the option. Looking forward to a PR.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1415.

**Pull request closed without merging**
