### PR TITLE
Replace Hashie::Mash with ActiveSupport::HashWithIndifferentAccess.

### PR DESCRIPTION
**Pull request by dblock**
Replaces #1594, includes a way to set the class name globally.

### CODE REVIEW

**Comment by dblock** [comment]
@namusyaka @marshall-lee @james2m Would appreciate comments/feedback will iterate to green and everyone being happy. I am a little concerned that we're losing method access, since it probably will affect quite a few people but I think it's the right thing to do.

**Comment by dblock** [comment]
💚

**Comment by james2m** [comment]
@dblock thanks for finishing that up, looks similar to what I have locally, I just didn't have time to polish up and complete as I'm traveling until 17th. The cleaned up tests is a big relief too! 😬

**Comment by dblock** [comment]
You've done an excellent job up this far @james2m, thanks for your big effort!

**Comment by namusyaka** [comment]
💚 👍 
I also agree that method access of parameters isn't good design.

**Comment by dblock** [comment]
How are we feeling about merging this?

**Comment by james2m** [comment]
I'm happy with it. Using it in a new app with Rails 5.1 release candidate. If I had more tinkering time I'd probably reorganise the files under /extensions as it feels like a dumping ground right now, but nothing functional.

**Comment by dblock** [comment]
I merged this, lets see what happens ;)

**Pull request merged**
