### PR TITLE
Add Rails 5 appraisal.

### PR DESCRIPTION
**Pull request by dblock**
Replacing https://github.com/ruby-grape/grape/pull/1456.

### CODE REVIEW

**Comment by dblock** [comment]
cc: @glaucocustodio, with build fixes for Rails 5, all issues are caused by rack-contrib not being compatible with rack 2.0 (see https://github.com/rack/rack-contrib/issues/127).

**Comment by glaucocustodio** [comment]
I saw it, checkout https://github.com/rack/rack/pull/1103.

**Comment by dblock** [comment]
That PR into Rack is great @glaucocustodio. I think I should still move forward with workarounds here (assuming I can fix the remaining build issues). Please do let me know if you feel otherwise.

**Comment by glaucocustodio** [comment]
As you prefer @dblock. Depending on `rack-jsonp` instead `rack-contrib` seems better if possible.

**Comment by dblock** [comment]
Yep, we have a winner with `rack-jsonp`. Merging.

**Pull request merged**
