### PR TITLE
Failing test case catch-all route - #1081

### PR DESCRIPTION
**Pull request by wagenet**

### CODE REVIEW

**Comment by dblock** [comment]
This looks like a succeeding test :)

**Comment by wagenet** [comment]
Ok... that's odd. It failed for me locally.

**Comment by wagenet** [comment]
```
% rspec spec/grape/api_spec.rb:483                                                                                                  
Run options: include {:locations=>{"./spec/grape/api_spec.rb"=>[483]}}

Grape::API
  .route
    allows for catch-all in a namespace (FAILED - 1)

Failures:

  1) Grape::API.route allows for catch-all in a namespace
     Failure/Error: expect(last_response.body).to eql 'catch-all'

       expected: "catch-all"
            got: ""

       (compared using eql?)
     # ./spec/grape/api_spec.rb:508:in `block (3 levels) in <top (required)>'

Finished in 0.0718 seconds (files took 0.56025 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/grape/api_spec.rb:483 # Grape::API.route allows for catch-all in a namespace
```

**Comment by dblock** [comment]
Oh it doesn't look like anything ran?!

**Comment by wagenet** [comment]
@dblock I just rebased on master to get a new push. I'm still not seeing anything running. Is your integration busted?

**Comment by dblock** [comment]
That would make sense, since we moved repo owners! Fixing.

**Comment by wagenet** [comment]
Now tests fail :)

**Comment by dblock** [comment]
Success! :+1: :)

**Comment by dblock** [comment]
I believe this is fixed with the new router, @wagenet can you rerun these against HEAD please?

**Comment by wagenet** [comment]
@dblock I've rebased. Test is still failing.

**Comment by dblock** [comment]
Thanks @wagenet, @namusyaka if you have a moment I couldn't figure out what's wrong here.

**Pull request closed without merging**
