### PR TITLE
added note for avoid using :default on exactly_one_of

### PR DESCRIPTION
**Pull request by gencer**

### CODE REVIEW

**Comment by dblock** [comment]
This is related to #1717. I think this note makes it even more confusing, what should happen is that if you specify a default for more than one parameter (or any parameter) in a mutually exclusive relationship you should get an error on mounting the API.

**Comment by gencer** [comment]
But, I am sure people will fall into this if they simply forget :default in their optional params when they are using exactly_one_of. To prevent this, and let them know that those params should not exists even as a nil, we should add a note/warning.

Still, It is your decision of course :)

**Comment by gencer** [comment]
And you think the right thing. I agree on that.

I amend and squash changes (removed changelog but change the readme)

**Comment by dblock** [comment]
Thanks, merged.

**Pull request merged**
