### PR TITLE
Align implementation with Rack SPEC

### PR DESCRIPTION
**Pull request by ioquatix**
And update specs/expand testing.

### CODE REVIEW

**Comment by ioquatix** [comment]
I think this is okay to merge.

**Comment by dblock** [comment]
👍 merged, although I do worry about `.to_a` causing unexpected regressions (eg. streaming response)

**Comment by ioquatix** [comment]
Rack middleware must return an array of `[status, headers, body]` and all the `.to_a` method is doing is forcing that. It doesn't change any of the individual fields, e.g. `body` is still `body`. You shouldn't be returning a rich object in order to support streaming.

That being said, I understand your concern.

**Comment by nbulaj** [comment]
Actually this changes broked our app after upgrade, check this one: https://github.com/ruby-grape/grape/issues/2030#issuecomment-624676579

**Comment by ghiculescu** [comment]
Should we add something about this to https://github.com/ruby-grape/grape/blob/master/CHANGELOG.md#130-20200111

I ended up here looking into https://github.com/ruby-grape/grape/issues/1966 and it'd be great if the changelog called that out somehow

**Comment by dnesteryuk** [comment]
@ghiculescu of course, go ahead! :slightly_smiling_face:

**Comment by ghiculescu** [comment]
> @ghiculescu of course, go ahead! 🙂

https://github.com/ruby-grape/grape/pull/2059

**Pull request merged**
