### PR TITLE
Update links in README

### PR DESCRIPTION
**Pull request by mr-dxdy**

### CODE REVIEW

**Comment by dblock** [comment]
Thanks. Can we actually roll out [danger-toc](https://github.com/dblock/danger-toc) here instead? We already have danger setup for Grape so this should be as simple as adding a few things to Gemfile and Dangerfile and making sure it reports errors accordingly for broken TOC.

**Comment by mr-dxdy** [comment]
@dblock, why didn't Travis trigger a build here?

**Comment by dblock** [comment]
screen shot 2018-04-02 at 9 19 51 am

I'll email them. I've had this before.

**Comment by mr-dxdy** [comment]
I think that pull request done. 

The gem "danger-toc" is enabled. [Link](https://github.com/ruby-grape/grape/blob/master/Dangerfile#L2)
I run command `bundle exec danger pr https://github.com/ruby-grape/grape/pull/1753` and get results:

```
Results:

Warnings:
- [ ] Unless you're refactoring existing code, please update CHANGELOG.md.

Markdown:                                                                                                                                                                    
Here's an example of a CHANGELOG.md entry:

```markdown
* [#1753](https://github.com/ruby-grape/grape/pull/1753): Update links in readme - [@mr-dxdy](https://github.com/mr-dxdy).
```

**Comment by dblock** [comment]
@mr-dxdy Squash the commits and Travis will trigger a build. They "cleared the abuse", whatever that means.

**Comment by mr-dxdy** [comment]
@dblock,  i think this pull request does not need to be added to the CHANGELOG

**Comment by dblock** [comment]
Perfect, merged, thank you.

**Pull request merged**
