### PR TITLE
Replace let_it_be by before :all

### PR DESCRIPTION
**Pull request by ericproulx**
Hello,

`let_it_be` seams fleaky in the test suite. I removed it and use before :all instead

### CODE REVIEW

**Comment by dblock** [comment]
Looks like a legit build failure in https://github.com/ruby-grape/grape/runs/4422845217?check_suite_focus=true

**Comment by ericproulx** [comment]
I can reproduce every time with the same seed. Another test is changing something. I'll find it. Do you want to keep TestProf ? Seems more ruby than using `before :all` with instance variable.

**Comment by ericproulx** [comment]
It feels like the global settings somehow is not resetted even with new instance.

I solved the problem by calling ::Logger.new instead of double
Screen Shot 2021-12-05 at 17 21 25

**Comment by ericproulx** [comment]
Looks like truffle-ruby doesnt like unicode in instance_variable

https://github.com/ruby-grape/grape/runs/4423127949?check_suite_focus=true

"@😸" is let_it_be prefix.

**Comment by dblock** [comment]
I don't care as much about truffle ruby, but this does need to be rebased and any other legit build failure fixed.

Btw, no need to include in CHANGELOG any changes that were added/removed within the release. Like when you add a feature, then fix a bug in that feature in the same release there's no need to changelog that you fixed a bug as it was never shipped.

**Pull request closed without merging**
