### PR TITLE
Add Skylight to Performance section

### PR DESCRIPTION
**Pull request by wagenet**

### CODE REVIEW

**Comment by wagenet** [comment]
@dblock can this be merged? The Grape stuff is now in a full release (0.8.0) of the skylight gem.

**Comment by dblock** [comment]
I'll merge this. Generally I think we need to start taking links like these out of here and into ruby-grape.org.

**Comment by dblock** [comment]
So @wagenet you definitely want this on http://www.ruby-grape.org/projects/ as well. And maybe you can remove this list from Grape's README and link to a section on the website? Something similar would be useful for entities and such.

**Comment by wagenet** [comment]
@dblock are you thinking of this as a top-level section on the website? or a sub-section?

**Comment by dblock** [comment]
In projects, not top level.

**Pull request merged**
