### PR TITLE
Spec and fix for #1721.

### PR DESCRIPTION
**Pull request by dblock**
#1721

With the catch all route fails to find v2.

@namusyaka I tried to fix this but failed, maybe you'll have a moment to help?

### CODE REVIEW

**Comment by zherr** [comment]
@dblock Take a look at https://github.com/dblock/grape/pull/2 when you get a chance.

**Comment by dblock** [comment]
Combine my specs and your code @zherr and PR the whole thing, thanks for the fix!

**Comment by dblock** [comment]
I just merged that PR @zherr lets see if this passes and it's good to go if so.

**Comment by zherr** [comment]
Cheers! 🍻

**Pull request merged**
