### PR TITLE
Remove hashie dependency

### PR DESCRIPTION
**Pull request by etehtsea**
Because less dependencies is much better than more.
This is breaking change and I'm open for discussion.

Additional point for doing this is that in our app we are still locked to `hashie ~> 2.1.1` (we aren't using it in the project) just because later versions require `https://github.com/Maxim-Filimonov/hashie-forbidden_attributes` gem. This is kinda weird from my point of view to require "workaround" gem for internal grape dependency.

P.S. Spec suite is green, but I'm not sure that there is no unexpected behavior changes.

### CODE REVIEW

**Comment by etehtsea** [comment]
Didn't see that it was already made in https://github.com/ruby-grape/grape/pull/1279
Leaving it open because this PR is based on `HashWithIndifferentAccess`.

**Comment by dblock** [comment]
I think we want this to be a plain `Hash`, *and* we want to provide a way to wrap that with either a `Hashie::Mash` class, `HashWithIndifferentAccess` or whatever else for backward compatibility. I'd take a PR that accomplishes that.

**Comment by nbulaj** [comment]
I agree that Grape needs to delete `Hashie` dependency and work with any any class that maybe respond to `to_h`. @dblock what do you think about that?

**Comment by dblock** [comment]
I'm with you @nbulaj, see above for more detailed comments about what I suggest the plan to move forward could be.

**Comment by etehtsea** [comment]
@dblock I couldn't make it, so please reopen it as issue if needed.

**Comment by dblock** [comment]
Lets leave this open, it's a valid feature request.

**Comment by etehtsea** [comment]
@dblock I meant that this PR won't be ever merged so it will be better to open issue that someone could assign to.

**Comment by dblock** [comment]
Lets leave this as is. Issues, PRs, all the same ;)

**Comment by dblock** [comment]
Closing via #1610.

**Pull request closed without merging**
